version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
  groups:
    arrow-deps:
      patterns:
          - "arrow"
          - "arrow-schema"
          - "parquet"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
