[package]
name = "arrow-tools"
version = "0.0.1"
edition = "2021"
authors = ["Dominik Moritz <domoritz@cmu.edu>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/domoritz/arrow-tools"

[dependencies]
